### ISSUE TITLE
input_opencv.so cannot be found

### ISSUE THREAD

**Issue by mzwtjp** [beagleboard/beaglebone-ai#27]
I followed the tidl introduction to build and run classification demo, but I get the folloeing.
(I have update/upgraded my environmment before trying to build this sample.)
Anything I am missing?

>sudo mjpg_streamer -i "input_opencv.so -r 640x480 --filter ./classification.tidl.so" -o "output_http.so -p 8080 >-w /usr/share/mjpg-streamer/www"
>[sudo] password for debian:
>MJPG Streamer Version.: 2.0
>ERROR: could not find input plugin
>       Perhaps you want to adjust the search path with:
>       # export LD_LIBRARY_PATH=/path/to/plugin/folder
>       dlopen: input_opencv.so: cannot open shared object file: No such file or directory
>/var/lib/cloud9/common/Makefile:167: recipe for target 'start' failed
>make: *** [start] Error 1
>rm /tmp/cloud9-examples/classification.tidl.o

No input_opencv.so:

>debian@beaglebone:/var/lib/cloud9$ ls /usr/lib/mjpg-streamer/
>input_file.so  input_http.so  input_uvc.so  output_file.so  output_http.so  output_rtsp.so  output_udp.so

**Comment by jadonk** [comment]
```
sudo apt update
sudo apt install -y mjpg-streamer-opencv-python
```
