### ISSUE TITLE
Step model

### ISSUE THREAD

**Issue by rjremiz** [beagleboard/beaglebone-ai#32]
Hello, would be possible to release  step model of BeagleBone AI?

**Comment by laurencedv** [comment]
pretty please?

**Comment by jadonk** [comment]
I'll look into it.

**Comment by mkjel** [comment]
Hi, any progress on exporting the .stp file?

**Comment by jadonk** [comment]
@FionaYu20180326 Do you have the ability to generate a STEP (.stp) model?

**Comment by FionaYu20180326** [comment]
BeagleBone AI Rev A1, right? I can commit it on May 19th.

**Comment by jadonk** [comment]
Yes, rev A1.

**Comment by jadonk** [comment]
https://github.com/beagleboard/beaglebone-ai/pull/43

**Comment by jadonk** [comment]
https://github.com/beagleboard/beaglebone-ai/blob/master/Mechanical/PCBA_BeagleBone_AI_Rev_A1.stp

**Comment by laurencedv** [comment]
Thanks you very much! Will be able to do our custom test-casing now :D
