### ISSUE TITLE
BeagleBone AI SPI Enable

### ISSUE THREAD

**Issue by Zeki411** [beagleboard/beaglebone-ai#35]
Hello, Everyone !
i am so brand new to BeagleBone AI (AM5729) and now i am trying to enable SPI on it. I have tried turn it on by adding some following line in uEnv.txt but it didn't work:

cmdline=coherent_pool=1M net.ifnames=0 quiet cape_universal=enable
uboot_overlay_addr4=/lib/firmware/BB-SPIDEV0-00A0.dtbo
uboot_overlay_addr5=/lib/firmware/BB-SPIDEV1-00A0.dtbo

Can anyone help me, pls ?

**Comment by Lander-liu** [comment]
I met the same problem about uart ,so anyone help us?

**Comment by silver2row** [comment]
Hello,

I think, and I am not affiliated at all except that I use their products, making a .dts file is a starter and then turning that into a .dtbo w/ the help of their scripts could be beneficial.

Seth

**Comment by silver2row** [comment]
Hello Again,

Try here: https://groups.google.com/g/beagleboard/c/NFMZiBIPvno/m/2t_Oczx-AQAJ

Seth
