### ISSUE TITLE
Editor Eagle

### ISSUE THREAD

**Issue by kissup77** [beagleboard/beaglebone-ai#44]
Using latest eagle SW, I had opened files but it shows error "Start tag  ..."

**Comment by kissup77** [comment]
I tried to open it with the latest EAGLE software

**Comment by pdp7** [comment]
What files are you attempting to open in EAGLE

The BeagleBone AI was designed in Cadance Allegro.

BeagleBoard.org Foundation has contracted KiCad Professional Services to convert the design to KiCad, which is open source CAD software.

**Comment by kissup77** [comment]
OMG, I thought it was designed with EAGLE. Let me try to open with Cadence Allegro

**Comment by kissup77** [comment]
Actually I will need x,y coordinates to make samples of it. Can you share it with me?

**Comment by pdp7** [comment]
@kissup77 do you mean centroid coordinates for a Pick n Place machine?

@jadonk do we have that information?

**Comment by jadonk** [comment]
@pdp7 It should be part of the generated Gerbers, which we need to clean up. I might be able to regenerate it. Ideally, we'd verify against the production files.

**Comment by kissup77** [comment]
One of Cadence Expert provides me x,y coordinates information files. It is resolved. Thanks.
