### ISSUE TITLE
SD Card Expansion

### ISSUE THREAD

**Issue by bogdanys** [beagleboard/beaglebone-ai#64]
Hi everyone,
I own a BeagleBone AI, and the operating system runs on the eMMC. Storage is limited to only 15GB. In this sense I want to add a SD card that I can use only for additional storage space, without running the operating system on it, but I don’t know how to do that. I saw here, that if I remove R689 everything should work fine, but I'm wondering if it is other option.

**Comment by MehdiGuizani** [comment]
Virtualization?

**Comment by MehdiGuizani** [comment]
Try a virtual environment like venv..
With the computing power the beaglebone has it should be able to run pimox a small version of proxmox on the system 👍🏼

**Comment by jadonk** [comment]
For usage questions, ask on forum.beagleboard.org.
